import type { Metadata } from "next";
import { Instrument_Sans, Atkinson_Hyperlegible, Outfit } from "next/font/google";
import "./globals.css";
import { Providers } from '@/components/providers'
import GoogleAnalytics from '@/components/GoogleAnalytics'

// Logo font - Instrument Sans with multiple weights
const instrumentSans = Instrument_Sans({
  variable: "--font-instrument",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Regular (400) for "Style", Medium (500) for "Luxe"
  display: 'swap',
  preload: true,
});

// Heading font - Outfit
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: 'swap',
  preload: true,
});

// Body font - Atkinson Hyperlegible
const atkinsonHyperlegible = Atkinson_Hyperlegible({
  variable: "--font-atkinson",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: 'swap',
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className={`${instrumentSans.variable} ${outfit.variable} ${atkinsonHyperlegible.variable} antialiased`}
      >
        <GoogleAnalytics />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
